project:
  type: website
website:
  navbar:
    right:
      - href: index.qmd
        text: Home
      - working_papers.qmd
      #- projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/LeaPradella
      - icon: github
        href: https://github.com/LeaPradella
  sidebar: false
format:
  html:
    theme: lux
    css: 
    - styles.css
    - academicons.css
    #toc: true

editor: visual

