project:
  type: website
  output-dir: docs    # for publishing via github pages (don't forget to add the .nojekyll file to the docs)
  
website:
  navbar:
    right:
      - href: index.qmd
        text: Home
      - working_papers.qmd
      - dissertation.qmd
      - cv.qmd
      - teaching.qmd
    tools:
      - icon: envelope
        href: "mailto:lea.pradella@ps.au.dk" 
      - icon: github
        href: https://github.com/LeaPradella
  sidebar: false
  
format:
  html:
    theme: lux
    linkcolor: "#0096C7"
    css: 
    - styles.css
    - academicons.css
    #toc: true

editor: visual

