---
title: "Research"
---
 
::: {style="font-size: 95%;"}
#### {{< fa newspaper >}} Journal Articles

Bor, A., Marie, A., [Pradella, L.]{style="color:black;"}, Petersen, M. B. (2026) “[Social media users experience more political hostility in less economically equal and less democratic societies]{style="color:black;"}”. *Nature Human Behavior*. [Link to paper.](https://doi.org/10.1038/s41562-026-02432-5){target="_blank"} 

::: {.callout-note collapse="true" icon="false" appearance="simple"}
## Abstract

There is widespread concern about the hostility of political discussions on social media but there is no consensus about the underlying dynamics. In particular, the relationship between online hostility and the broader sociopolitical context has received less attention, in part because of limited research outside Western countries. Here, we report results from observational data collected through quota-sampled online surveys in 30 countries across six continents (N = 15,202) about experiences of online hostility. Our findings show that people in less democratic and less economically equal countries experience more hostility online. We also find that, in every country, respondents who are hostile online are also hostile offline, and that these people score higher in status-seeking motivations. Exploratory analyses suggest that less democratic societies include more status-motivated individuals and young men—groups showing higher hostility on average. Overall, these findings highlight how online political hostility is intertwined with wider societal tensions.
:::

[Pradella, L.]{style="color:black;"} (2024). [Testing the social pressure hypothesis: Does in-party social pressure reduce out-party empathy?]{style="color:black;"}. *PNAS nexus*, 3(10), pgae358. [Link to paper.](https://doi.org/10.1093/pnasnexus/pgae358){target="_blank"} 

::: {.callout-note collapse="true" icon=false appearance="simple"} 
## Abstract 

Empathy is considered one of the most critical components for bridging political divides and reducing animosity between political groups. Yet, empathy between political opponents is rare. There is a growing concern that partisans do not empathize with out-partisans because they feel social pressure from fellow in-partisans not to do so. This article examines this social pressure hypothesis and draws two conclusions. First, on the surface, the hypothesis seems plausible: citizens perceive fellow in-partisans as comparatively disapproving of and reluctant to engage in out-party empathy, and naïve cross-sectional analyses suggest that this perception translates into lower empathy towards out-partisans. Second, however, experimental data suggest that this relationship is not causal. Expecting disapproval from fellow in-party members for empathizing with out-partisans does not lead to a significant reduction in intentions to empathize with out-partisans. Rather, exploratory analyses suggest that social pressure by the in-party increases empathy toward out-partisans and triggers disappointment toward in-partisans. This implies that partisans can resist social pressure from the in-party and might even compensate for in-partisans’ lack of out-party empathy. The results are supported by original cross-sectional and experimental survey data (N = 2,535⁠) collected in the United States, an arguably most likely case for in-party social pressure to shape partisans’ intentions. The results have important implications for understanding the causes of and viable strategies for building empathy across political divides.
:::

Dias, N. C., Aarslew, L. F., Frederiksen, K. V. S., Lelkes, Y., [Pradella, L.]{style="color:black;"}, & Westwood, S. J. (2024). [Correcting misperceptions of partisan opponents is not effective at treating democratic ills.]{style="color:black;"} *PNAS nexus*, 3(8), pgae304. [Link to paper.](https://doi.org/10.1093/pnasnexus/pgae304){target="_blank"}

::: {.callout-note collapse="true" icon="false" appearance="simple"}
## Abstract

Many warn that the United States is on the brink of democratic collapse, because partisan animosity, support for partisan violence, and support for undemocratic practices are on the rise. Quelling some fears, scholars have offered interventions that use messages to correct misperceptions about citizens’ partisan opponents (the “out-party”). In this article, we provide evidence that the effects of these interventions are not as robust or consistent as hoped. First, we use panel data (N = 9,810⁠) to show that perceptions of the out-party are highly variable. This suggests that these perceptions are weakly held and thus unlikely to be a significant cause of hostile attitudes. The oscillation of perceptions over time also suggests that, for many, any effect of corrections would likely be overwhelmed in just 1 month. Second, in a meta-analysis of 67 statistical tests from 12 studies in eight papers, we document that current evidence on the efficacy of corrections is weak. Third and finally, in pre-registered experiments (n = 2,846⁠), we find that changing Americans’ perceptions of the out-party’s demographics, policy attitudes, and support for undemocratic practices has no consistent effect on partisan animosity, support for partisan violence, or support for undemocratic practices. These observations suggest that correcting misperceptions of the out-party is not a panacea for our democratic ills.
:::

<br>

#### {{< fa pen-to-square >}} Working Papers

[Pradella, L.]{style="color:black;"}, Selmer, S. B., & Petersen, M. B. "[How Different Discussion Formats Shape Political Disagreement Between Citizens: Comparing Low and High Cue Interactions]{style="color:black;"}", *under review*. [Link to paper.](https://osf.io/preprints/psyarxiv/8c72w_v1){target="_blank"}

::: {.callout-note collapse="true" icon="false" appearance="simple"}
## Abstract

Over the past decade, political interactions have increasingly moved to text-based online environments. This shift has raised widespread concern that the low richness of online communication, i.e., the lack of nonverbal and interpersonal cues, undermines productive political discourse. We tested this by organizing 473 dyadic discussions between 946 Danish citizens with opposing political views, randomly assigning them to discuss contentious issues of immigration and unemployment benefits either in (1) a low-cue text-based chat or (2) a high-cue face-to-face video interaction. We examined how these conversations differed along three dimensions: (a) the tone of discussion, (b) perceptions of discussion partners, and (c) willingness to engage in political discussion. Our results challenge the assumption that low-cue text-based discussions are inherently detrimental to productive political discourse. We find no evidence that text-based discussions increase hostility. In fact, hostile language was virtually absent across both formats, and exploratory analyses indicate that participants held less hostile views toward political out-groups after the discussion, regardless of format. Rather than low-cue interactions undermining political discourse, we find that high-cue interactions make it a more positive experience: participants in high-cue discussions evaluated their partners more positively, felt greater social closeness, and expressed more willingness to engage in similar discussions again. Exploratory analyses further showed that face-to-face discussants enjoyed the conversation more and reported greater learning. These findings show that productive discussions across political differences are possible even in low-cue environments, while suggesting that richer, high-cue formats hold greater potential for more positive experiences in interactions across political differences. 

:::

[Pradella, L.]{style="color:black;"} "[Rethinking Accuracy Motivations: How Empathic vs. Factual Accuracy Goals Influence Online Political Hostility]{style="color:black;"}", *under review*.

::: {.callout-note collapse="true" icon="false" appearance="simple"}
## Abstract

How can interactions between political opponents on social media become less hostile? According to motivated reasoning theory, reducing such hostility may require motivating individuals to seek accuracy goals rather than directional goals. But what kind of accuracy matters? This study distinguishes between two types: factual accuracy, the goal of determining what is objectively true, and empathic accuracy, the goal of accurately understanding opponents’ subjective experiences. In a pre-registered survey experiment, 3051 U.S. participants were motivated by video prompts to approach a social media post with an opposing view on immigration with different goals in mind. Results show that motivating individuals to adopt empathic accuracy goals (vs. factual accuracy goals and directional goals) reduces hostility toward and perceived superiority over political opponents, and increases agreement with pro- but not anti-immigration views. These findings highlight the importance of differentiating between different types of accuracy goals that people bring to political interactions and suggest that motivating people to accurately understand the other side can reduce online political hostility.
:::

[Pradella, L.]{style="color:black;"} "[When Out-Partisans Understand: The Impact of Out-Party Empathy on Third-Person Observers]{style="color:black;"}", *under review*.

::: {.callout-note collapse="true" icon="false" appearance="simple"}
## Abstract

Empathy toward out-partisans is considered key to reducing hostility. Most research studies empathy in one-on-one interactions. However, political interactions are more often passively observed than actively participated in. This study therefore examines how observers react when out-partisans express empathy. In a pre-registered survey experiment with 3,324 U.S. participants, observers reported less hostility, more empathy, and more comfort discussing politics when out-partisans express empathy (vs. no empathy). However, these effects disappear once empathic out-partisans also express disagreement, suggesting em-pathy has benefits only when expressed purely. Exploratory analyses suggest why: observers interpret empathic messages not only as expressions of empathy, but also as agreement and atypicality. Thus, the benefits of empathy stem not only from empathy itself, but also from what else it signals. These findings highlight both the promise of empathy for improving political relations beyond dyadic interactions and the challenge of navigating political differences without losing the ability to disagree.
:::


<br>

#### {{< fa square-poll-horizontal >}} Reports

Andresen, M. J., Karg, S. T. S., Rasmussen, S. H. R., [Pradella, L.]{style="color:black;"}, Rasmussen, J., Lindekilde, L., & Petersen, M. B. (2022). "[Danskernes Oplevelse Af Had På Sociale Medier](https://pure.au.dk/portal/files/271291115/Danskernes_oplevelse_af_had_pa_de_sociale_medier_Rapport_Aarhus_Universitet_.pdf)." (English title: Danes’ experience of hate on social media). *Aarhus University*.

<br>

#### {{< fa spinner >}} Work in Progress

[Pradella, L.]{style="color:black;"}, Bøggild, T. "[Extremity Bias in Peer-to-Peer Communication]{style="color:black;"}"

[Pradella, L.]{style="color:black;"}, Petersen, M. B., Bøggild, T. “[When Posts Meet the Wrong Crowd: Audience Mismatch and Political Hostility on Social Media]{style="color:black;"}”.

:::::::
